spin_manifest_version = 2

[application]
name = "cqrs-rust"
version = "0.1.0"
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "A fairly simple CQRS implementation"

[[trigger.http]]
route = "/..."
component = "cqrs-rust"

[component.cqrs-rust]
source = "target/wasm32-wasi/release/cqrs_rust.wasm"
allowed_outbound_hosts = []
sqlite_databases = ["default"]

[component.cqrs-rust.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
